spring:
  redis:
    host: localhost
    password:
    port: 6379
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/jpa
    username: sa
    password: 1


    jpa:
      properties:
        hibernate:
          format_sql: true
          user_sql_cooments: true
      hibernate:
        ddl-auto: creat

  profiles:
    include: jwt