jwt:
  secret: Snd0QVBJU2VydmljZUFuZFdlYlNvY2tldFByb2plY3Q= #JwtAPIServiceAndWebSocketProject

  access:
    expiration: 86400 #3600*24
    header: Authorization

  refresh:
    expiration: 604800 #3600*24*7
    header: Authorization-refresh